define({
  root: ({
    _widgetLabel: "Query Elected Officials",
    fedLabel: "Federal",
    stateLabel: "State",
    countyLabel: "County",
    cityLabel: "City",
    othersLabel: "Others",
    usSenator: "U.S. Senator",
    name: "Name: ",
    term: "Term: ",
    moreInfo: "More information: ",
    clickHere: "Click here",
    usCongressRepTitle: "U.S. Congress Representative",
    dist: "District: ",
    showBoundary: "Show boundary",
    governorTitle: "Governor",
    txSenatorTitle: "Texas Senator",
    txHouseTitle: "Texas House Representative",
    countyJudgeTitle: "County Judge",
    county: "County: ",
    countyCommTitle: "County Commissioner",
    precinct: "Precinct: ",
    cityMayorTitle: "City Mayor",
    city: "City: ",
    cityCouncilTitle: "City Council Member(s)",
    distRepTitle: "District Representative",
    atLargeMemberTitle: "At-Large Members",
    of: " of ",
    schoolDistTitle: "School Board Trustee(s)",
    schoolDist: "School District: ",
    distTrusteeTitle: "District Trustee",
    exportBtn: "Export"
  }),
});