define({
  root: ({
    _widgetLabel: "Query Results",
    _featureAction_ShowVertex: "Show Vertex Count",
    resourceLabel: "Resources",
    demoLabel: "Demographics",
    specialLabel: "Specials",
    empLabel: "Employments",
    exportBtn: "Export",
	clearResultsBtn: "Clear results",
	resourcesTitle: "Service area resources",
	demoResultsTitle: "Service area basic demographics",
	specialResultsTitle: "Service area special demographics",
	empResultsTitle: "Service area employments",
	resource: "Resource",
	demographics: "Demographics",
	naics: "2-Digit NAICS Sector",
	count: "Count",
	business: "Business",
	employee: "Employee",
	totalAEL: "AEL provider",
	totalExoffender: "Ex-offender resource",
	totalETPS: "Gulf coast region ETPS",
	totalParole: "Parole office",
	totalReentry: "Re-entry resource",
	totalCO: "Career office",
	totalVR: "Vocational rehab office",
	totalLibrary: "Library",
	totalJobAd: "Job ad",
	totalPop: "Population",
	totalFemale: "Female",
	totalMale: "Male",
	totalUnder18: "Age under 18",
	total1824: "Age 18 - 24",
	total2534: "Age 25 - 34",
	total3544: "Age 35 - 44",
	total4554: "Age 45 - 54",
	total5564: "Age 55 - 64",
	total6574: "Age 65 - 74",
	totalAbove75: "Age above 75",
	totalNoEnglish: "English not well",
	totalNoHS: "No high school diploma",
	totalHS: "High school graduate",
	totalSomeCollege: "Attended some college",
	totalAssociates: "Associate's degree",
	totalBachelors: "Bachelor's degree",
	totalPostGrad: "Post-graduate degrees",
	totalDisabled: "With disability",
	totalVeteran: "Veteran",
	totalUnemployed: "Unemployed",
	totalPoverty: "In poverty",
	totalPubAssist: "Received public assistance",
	totalDisconnYouth: "Disconnected youth",
	totalNAICS: "All occupations",
	totalCO: "CO Workforce Solutions Career Office",
	totalIO: "IO Workforce Solutions Itinerant Office",
	total11: "11 Agriculture, Forestry, Fishing and Hunting",
	total21: "21 Mining, Quarrying, and Oil and Gas Extraction",
	total22: "22 Utilities",
	total23: "23 Construction",
	total3133: "31 - 33 Manufacturing",
	total42: "42 Wholesale Trade",
	total4445: "44 - 45 Retail Trade",
	total4849: "48 - 49 Transportation and Warehousing",
	total51: "51 Information",
	total52: "52 Finance and Insurance",
	total53: "53 Real Estate and Rental and Leasing",
	total54: "54 Professional, Scientific, and Technical Services",
	total55: "55 Management of Companies and Enterprises",
	total56: "56 Administrative and Support and Waste Management and Remediation Services",
	total61: "61 Educational Services",
	total62: "62 Health Care and Social Assistance",
	total71: "71 Arts, Entertainment, and Recreation",
	total72: "72 Accommodation and Food Services",
	total81: "81 Other Services (except Public Administration)"
  }),
});