define({
  root: ({
    _widgetLabel: "Query Geometry",
    _featureAction_ShowVertex: "Show Vertex Count",
    bufferLabel: "Buffer",
    zipLabel: "ZIP Code",
    countyLabel: "County",
    searchRadiusTitle: "Enter a search radius",
	searchRadiusText: "Search within (miles):",
	bufferNote: "Enter a buffer distance or use the slider and drop a point on map",
	selectZIPCodeTitle: "Select a ZIP Code area",
	selectZIPCodeText: "ZIP Code:",
	zipNote: "Enter a ZIP Code and press Enter or use the select tool",
	selectCountyTitle: "Select a County",
	selectCountyText: "County:",
	countyNote: "Select a county or use the select tool",
	default: "--Select a county--",
	austin: "Austin",
	brazoria: "Brazoria",
	chambers: "Chambers",
	colorado: "Colorado",
	fortBend: "Fort Bend",
	galveston: "Galveston",
	harris: "Harris",
	liberty: "Liberty",
	matagorda: "Matagorda",
	montgomery: "Montgomery",
	walker: "Walker",
	waller: "Waller",
	wharton: "Wharton",
	calculateBtn: "Calculate",
    showResultsBtn: "Show results"
  }),
});